# Generated by Django 5.2.8 on 2025-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
